version: 1

merge:
  trigger:
    labels: ["merge when ready"]
    comment_substrings: ["MERGE WHEN READY"]
  ignore:
    labels: ["do not merge"]
    comment_substrings: ["==DO_NOT_MERGE=="]
  method: squash
  # merge_method:
  #   - method: squash
  #     trigger:
  #       labels: ["merge when ready"]
  #   - method: merge
  #     trigger:
  #       labels: ["merge dependabot"]
  options:
    squash:
      title: "github_default_title"
      body: "pull_request_body"
    merge:
      title: "github_default_title"
      body: "pull_request_title"
  delete_after_merge: true
  allow_merge_with_no_checks: true

update:
  trigger:
    labels: ["wip", "update me"]
